version: '3'
services:
  my-postgres:
    image: postgres
    ports:
      - "8888:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./dbscript.sql:/docker-entrypoint-initdb.d/create_tables.sql
  app:
    depends_on:
      - postgres
    build: ./expense-reimbursement-spring
    restart: on-failure
    #env_file: ./.env
    ports:
      - 4444:9999
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgres://mysqldb:5432/project2",
        "spring.datasource.username" : "postgres",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: